// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-lieJiGev7JFV1emZHQVSMJcPerPhjWI',
    appId: '1:324192354539:web:fc5e37e7b3dafdaeeefeae',
    messagingSenderId: '324192354539',
    projectId: 'socialmediaapp-e9960',
    authDomain: 'socialmediaapp-e9960.firebaseapp.com',
    storageBucket: 'socialmediaapp-e9960.firebasestorage.app',
    measurementId: 'G-YFP0TM77WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSeSkRdvCy6AG8OoO5DraPcmfjBgc8naU',
    appId: '1:324192354539:android:5f0b7f15e54a4d22eefeae',
    messagingSenderId: '324192354539',
    projectId: 'socialmediaapp-e9960',
    storageBucket: 'socialmediaapp-e9960.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFm3gbEvu8i6bm-rIBm1dLYNm_nhmj9_8',
    appId: '1:324192354539:ios:700f9f9f171fd1a9eefeae',
    messagingSenderId: '324192354539',
    projectId: 'socialmediaapp-e9960',
    storageBucket: 'socialmediaapp-e9960.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );
}
